### ISSUE TITLE
GeoIP Database and Flags

### ISSUE THREAD

**Issue by glennzw** [SneakersInc/HoneyMalt#3]
Great transforms, thanks! Two small things I noticed whilst experimenting:
1. The GeoIP database is defined in HoneyMalt.conf, but then explicitly referenced in kippogeoip.py
2. The flag lookup fails for the UK - it tried to reference gb.png which 404s, rather than uk.png.

**Comment by catalyst256** [comment]
Hi Glenn,

Well spotted I will sort out those two issues tonight.

Thanks,
Adam

**Comment by catalyst256** [comment]
Hi Glenn,

I've pushed the change to the geoip lookup to use the value from the HoneyMalt.conf file and I've also (hopefully) sorted the flag issue out. When you get a chance can you test it for me? I can only find Chinese connections from my honeypot.

Thanks.

**Comment by catalyst256** [comment]
Close issue, changes made and no feedback so will assume successful.
